import { test, expect } from '@playwright/test';
test.describe('SauceDemo - Comprehensive E2E Flow', () => {
  test('complete shopping flow with multiple products', async ({ page }) => {
    await page.goto('https://www.saucedemo.com/inventory.html', {
      waitUntil: 'domcontentloaded',
    });
    await page.waitForLoadState('networkidle', { timeout: 5000 }).catch(() => {
    });
    await expect(page.locator('.inventory_list')).toBeVisible({ timeout: 10000 });
    await expect(page.locator('#react-burger-menu-btn')).toBeVisible();
    await expect(page.locator('#shopping_cart_container')).toBeVisible();
    await expect(page).toHaveTitle(/Swag Labs/i);
    const initialProducts = await page.locator('.inventory_item_name').allTextContents();
    await page.selectOption('.product_sort_container', 'az');
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    const sortedAZ = await page.locator('.inventory_item_name').allTextContents();
    expect(sortedAZ).toEqual([...sortedAZ].sort());
    await page.selectOption('.product_sort_container', 'za');
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    const sortedZA = await page.locator('.inventory_item_name').allTextContents();
    expect(sortedZA).toEqual([...sortedZA].sort().reverse());
    await page.selectOption('.product_sort_container', 'lohi');
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    const prices = await page.locator('.inventory_item_price').allTextContents();
    const priceValues = prices.map(p => parseFloat(p.replace('$', '')));
    const sortedPrices = [...priceValues].sort((a, b) => a - b);
    expect(priceValues).toEqual(sortedPrices);
    await page.selectOption('.product_sort_container', 'hilo');
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    const firstProductName = await page.locator('.inventory_item_name').first().textContent();
    await page.locator('.inventory_item_name').first().click();
    await expect(page).toHaveURL(/.*inventory-item.html/);
    await expect(page.locator('.inventory_details_name')).toContainText(firstProductName);
    await expect(page.locator('.inventory_details_price')).toBeVisible();
    await expect(page.locator('.inventory_details_desc')).toBeVisible();
    await page.locator('button:has-text("Back")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    const firstItem = page.locator('.inventory_item').first();
    await expect(firstItem).toBeVisible();
    const firstProductTitle = await firstItem.locator('.inventory_item_name').textContent();
    await firstItem.getByRole('button', { name: /add to cart/i }).click();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('1');
    const secondItem = page.locator('.inventory_item').nth(1);
    const secondProductTitle = await secondItem.locator('.inventory_item_name').textContent();
    await secondItem.getByRole('button', { name: /add to cart/i }).click();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('2');
    const thirdItem = page.locator('.inventory_item').nth(2);
    const thirdProductTitle = await thirdItem.locator('.inventory_item_name').textContent();
    await thirdItem.getByRole('button', { name: /add to cart/i }).click();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('3');
    await page.locator('#shopping_cart_container').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/cart.html');
    const cartItems = page.locator('.cart_item');
    await expect(cartItems).toHaveCount(3);
    await expect(cartItems.nth(0).locator('.inventory_item_name')).toContainText(firstProductTitle);
    await expect(cartItems.nth(1).locator('.inventory_item_name')).toContainText(secondProductTitle);
    await expect(cartItems.nth(2).locator('.inventory_item_name')).toContainText(thirdProductTitle);
    await cartItems.nth(1).getByRole('button', { name: /remove/i }).click();
    await expect(cartItems).toHaveCount(2);
    await page.locator('button:has-text("Continue Shopping")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await expect(page.locator('.shopping_cart_badge')).toHaveText('2');
    const fourthItem = page.locator('.inventory_item').nth(3);
    const fourthProductTitle = await fourthItem.locator('.inventory_item_name').textContent();
    await fourthItem.getByRole('button', { name: /add to cart/i }).click();
    await expect(page.locator('.shopping_cart_badge')).toHaveText('3');
    await page.locator('#shopping_cart_container').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/cart.html');
    await expect(page.locator('.cart_item')).toHaveCount(3);
    await page.locator('button:has-text("Checkout")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-step-one.html');
    await page.fill('#first-name', 'John');
    await page.fill('#last-name', 'Doe');
    await page.fill('#postal-code', '12345');
    await expect(page.locator('#first-name')).toHaveValue('John');
    await expect(page.locator('#last-name')).toHaveValue('Doe');
    await expect(page.locator('#postal-code')).toHaveValue('12345');
    await page.locator('input[type="submit"]').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-step-two.html');
    await expect(page.locator('.cart_list')).toBeVisible();
    await expect(page.locator('.summary_info')).toBeVisible();
    const checkoutItems = page.locator('.cart_item');
    await expect(checkoutItems).toHaveCount(3);
    await expect(page.locator('.summary_info_label:has-text("Payment Information")')).toBeVisible();
    await expect(page.locator('.summary_info_label:has-text("Shipping Information")')).toBeVisible();
    await expect(page.locator('.summary_subtotal_label')).toBeVisible();
    await expect(page.locator('.summary_tax_label')).toBeVisible();
    await expect(page.locator('.summary_total_label')).toBeVisible();
    await page.locator('button:has-text("Finish")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-complete.html');
    await expect(page.locator('.complete-header')).toContainText('Thank you for your order!');
    await expect(page.locator('.complete-text')).toBeVisible();
    await page.locator('button:has-text("Back Home")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await expect(page.locator('.shopping_cart_badge')).not.toBeVisible();
    await page.locator('#react-burger-menu-btn').click();
    await page.waitForTimeout(300);
    await expect(page.locator('.bm-menu')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("All Items")')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("About")')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("Logout")')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("Reset App State")')).toBeVisible();
    await page.locator('.bm-item:has-text("All Items")').click();
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await page.waitForTimeout(500);
    await page.selectOption('.product_sort_container', 'lohi');
    await page.waitForLoadState('networkidle', { timeout: 3000 }).catch(() => {});
    const finalPrices = await page.locator('.inventory_item_price').allTextContents();
    const finalPriceValues = finalPrices.map(p => parseFloat(p.replace('$', '')));
    const finalSortedPrices = [...finalPriceValues].sort((a, b) => a - b);
    expect(finalPriceValues).toEqual(finalSortedPrices);
    await expect(page.locator('#react-burger-menu-btn')).toBeVisible();
    await expect(page.locator('.inventory_list')).toBeVisible();
    const productCount = await page.locator('.inventory_item').count();
    expect(productCount).toBeGreaterThan(0);
    console.log(`Comprehensive test completed successfully! Tested ${productCount} products.`);
  });
});