import { test, expect } from '@playwright/test';
test.describe('SauceDemo - Unoptimized Baseline', () => {
  test('complete shopping flow - UNOPTIMIZED', async ({ page }) => {
    test.setTimeout(60000);
    await page.goto('https://www.saucedemo.com/');
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.fill('#user-name', 'standard_user');
    await page.fill('#password', 'secret_sauce');
    await page.click('#login-button');
    await new Promise(resolve => setTimeout(resolve, 2000));
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.inventory_list')).toBeVisible();
    await expect(page.locator('#react-burger-menu-btn')).toBeVisible();
    await expect(page.locator('#shopping_cart_container')).toBeVisible();
    await expect(page).toHaveTitle(/Swag Labs/i);
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.selectOption('.product_sort_container', 'az');
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.selectOption('.product_sort_container', 'za');
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.selectOption('.product_sort_container', 'lohi');
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await page.selectOption('.product_sort_container', 'hilo');
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await new Promise(resolve => setTimeout(resolve, 500));
    const firstProductName = await page.locator('.inventory_item_name').first().textContent();
    await page.locator('.inventory_item_name').first().click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL(/.*inventory-item.html/);
    await expect(page.locator('.inventory_details_name')).toContainText(firstProductName);
    await page.locator('button:has-text("Back")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await new Promise(resolve => setTimeout(resolve, 500));
    const firstItem = page.locator('.inventory_item').first();
    const firstProductTitle = await firstItem.locator('.inventory_item_name').textContent();
    await firstItem.getByRole('button', { name: /add to cart/i }).click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.shopping_cart_badge')).toHaveText('1');
    const secondItem = page.locator('.inventory_item').nth(1);
    const secondProductTitle = await secondItem.locator('.inventory_item_name').textContent();
    await secondItem.getByRole('button', { name: /add to cart/i }).click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.shopping_cart_badge')).toHaveText('2');
    const thirdItem = page.locator('.inventory_item').nth(2);
    const thirdProductTitle = await thirdItem.locator('.inventory_item_name').textContent();
    await thirdItem.getByRole('button', { name: /add to cart/i }).click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.shopping_cart_badge')).toHaveText('3');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('#shopping_cart_container').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/cart.html');
    const cartItems = page.locator('.cart_item');
    await expect(cartItems).toHaveCount(3);
    await new Promise(resolve => setTimeout(resolve, 500));
    await cartItems.nth(1).getByRole('button', { name: /remove/i }).click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(cartItems).toHaveCount(2);
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('button:has-text("Continue Shopping")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await expect(page.locator('.shopping_cart_badge')).toHaveText('2');
    await new Promise(resolve => setTimeout(resolve, 500));
    const fourthItem = page.locator('.inventory_item').nth(3);
    const fourthProductTitle = await fourthItem.locator('.inventory_item_name').textContent();
    await fourthItem.getByRole('button', { name: /add to cart/i }).click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.shopping_cart_badge')).toHaveText('3');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('#shopping_cart_container').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.cart_item')).toHaveCount(3);
    await page.locator('button:has-text("Checkout")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-step-one.html');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.fill('#first-name', 'John');
    await page.fill('#last-name', 'Doe');
    await page.fill('#postal-code', '12345');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('input[type="submit"]').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-step-two.html');
    await expect(page.locator('.cart_list')).toBeVisible();
    await new Promise(resolve => setTimeout(resolve, 500));
    await expect(page.locator('.summary_info_label:has-text("Payment Information")')).toBeVisible();
    await expect(page.locator('.summary_info_label:has-text("Shipping Information")')).toBeVisible();
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('button:has-text("Finish")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/checkout-complete.html');
    await expect(page.locator('.complete-header')).toContainText('Thank you for your order!');
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('button:has-text("Back Home")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await expect(page.locator('.shopping_cart_badge')).not.toBeVisible();
    await new Promise(resolve => setTimeout(resolve, 500));
    await page.locator('#react-burger-menu-btn').click();
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page.locator('.bm-menu')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("All Items")')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("About")')).toBeVisible();
    await expect(page.locator('.bm-item:has-text("Logout")')).toBeVisible();
    await page.locator('.bm-item:has-text("All Items")').click();
    await page.waitForLoadState('load');
    await new Promise(resolve => setTimeout(resolve, 1000));
    await expect(page).toHaveURL('https://www.saucedemo.com/inventory.html');
    await new Promise(resolve => setTimeout(resolve, 500));
    await expect(page.locator('#react-burger-menu-btn')).toBeVisible();
    await expect(page.locator('.inventory_list')).toBeVisible();
    const productCount = await page.locator('.inventory_item').count();
    expect(productCount).toBeGreaterThan(0);
    console.log(`Unoptimized test completed. Tested ${productCount} products.`);
    console.log(`This is the BASELINE - compare with optimized version for performance gains!`);
  });
});